spring.application.name=backend

# Server port
server.port=${PORT:8080}

# DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Initial Admin
app.admin.username=${ADMIN_USERNAME}
app.admin.password=${ADMIN_PASSWORD}
app.admin.email=${ADMIN_EMAIL}
app.admin.full-name=${ADMIN_FULL_NAME:System Administrator}

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION:86400000}

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# =========================
#  File Storage
# =========================
# =========================
# File Storage
# =========================

app.storage.type=${STORAGE_TYPE:local}

# Local
app.storage.local-dir=${STORAGE_LOCAL_DIR:uploads}
app.storage.local-base-url=${STORAGE_LOCAL_BASE_URL:http://localhost:8080}

# Supabase
app.storage.supabase.url=${SUPABASE_URL:}
app.storage.supabase.secret-key=${SUPABASE_SECRET_KEY:}
app.storage.supabase.bucket=${SUPABASE_BUCKET:class-management}

# Upload limit
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB